spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: root
    driver-class: com.cj.jdbc.Driver

#Jpa settings
spring.jpa.hibernate.ddl-auto: update